/**
 * 历史星图 · 第一阶段数据种子
 * 覆盖范围：明朝、清朝、中华民国（大陆时期）
 * 说明：本文件提供可入库的基础朝代、人物、事件、关系数据，供开发/测试/演示使用。
 */

export const phase1Dynasties = [
  {
    id: 'ming',
    name: '明朝',
    fullName: '大明',
    englishName: 'Ming Dynasty',
    span: '1368—1644',
    founded: '明太祖朱元璋',
    capital: '南京、北京',
    ended: '崇祯帝朱由检自缢',
    summary: '明朝由朱元璋建立，是元朝之后的汉族大一统王朝。明代强化皇权、废丞相、设内阁，前期国力强盛，中后期财政、党争、边防和农民起义问题加剧，最终在内外压力下灭亡。',
    stats: [
      { label: '存续', value: '276年' },
      { label: '皇帝数', value: '16位' },
      { label: '都城', value: '南京→北京' },
      { label: '覆灭', value: '1644年李自成攻陷北京' },
    ],
    status: 'focus',
  },
  {
    id: 'qing',
    name: '清朝',
    fullName: '大清',
    englishName: 'Qing Dynasty',
    span: '1636—1912',
    founded: '清太宗皇太极（后金奠基者努尔哈赤）',
    capital: '盛京、北京',
    ended: '宣统帝溥仪退位',
    summary: '清朝是中国最后一个传统王朝。它由满洲统治集团建立，入关后统一全国，并在康雍乾时期形成辽阔疆域。晚清面对内乱与西方冲击，经历洋务、戊戌、立宪等改革，最终在辛亥革命后结束帝制。',
    stats: [
      { label: '存续', value: '276年（1636起算）' },
      { label: '皇帝数', value: '12位' },
      { label: '都城', value: '北京' },
      { label: '覆灭', value: '1912年辛亥革命后退位' },
    ],
    status: 'focus',
  },
  {
    id: 'roc',
    name: '中华民国',
    fullName: '中华民国（大陆时期）',
    englishName: 'Republic of China',
    span: '1912—1949',
    founded: '孙中山、南京临时政府',
    capital: '南京、北京、重庆等',
    ended: '1949年国民政府迁台',
    summary: '中华民国大陆时期是中国从帝制王朝向共和国家转型的阶段，经历北洋政府、国民政府、军阀混战、抗日战争和国共内战。它是现代中国政治制度、民族国家、党派政治和社会转型的重要阶段。',
    stats: [
      { label: '存续', value: '37年' },
      { label: '阶段', value: '北洋政府→国民政府' },
      { label: '核心转型', value: '帝制→共和' },
      { label: '结束', value: '1949年中华人民共和国成立' },
    ],
    status: 'focus',
  },
];

export const phase1Persons = [
  // 明朝皇帝与人物
  {
    id: 'hongwu',
    name: '朱元璋',
    alias: '明太祖 · 洪武',
    born: 1328,
    died: 1398,
    dynastyId: 'ming',
    roles: ['开国皇帝', '明朝奠基者'],
    shortIntro: '明朝开国皇帝，出身贫寒，推翻元朝，建立大明，强化皇权，废丞相，设内阁雏形。',
    fullIntro: '明太祖朱元璋（1328—1398），幼名重八，濠州钟离人。元末参加红巾军，先后击败陈友谅、张士诚等割据势力，北伐驱逐元廷，1368年称帝，国号大明，年号洪武。在位期间废除丞相制度，六部直接对皇帝负责，设立锦衣卫，推行卫所制度，颁布《大明律》，为明代高度集权体制奠定基础。',
    achievements: ['推翻元朝，统一全国', '废除丞相，强化皇权', '建立卫所兵制', '颁布《大明律》'],
    controversy: '晚年大兴党狱，诛杀功臣；推行严刑峻法，社会控制严密。',
    quote: '驱逐胡虏，恢复中华。',
    quoteSource: '《谕中原檄》',
    works: ['《大明律》', '《御制大诰》'],
    lifeEvents: [
      { y: 1328, t: '出生于濠州钟离贫苦农家' },
      { y: 1352, t: '投奔郭子兴红巾军' },
      { y: 1368, t: '称帝，建立明朝' },
      { y: 1380, t: '废丞相，权分六部' },
      { y: 1398, t: '病逝，葬明孝陵' },
    ],
  },
  {
    id: 'yongle',
    name: '朱棣',
    alias: '明成祖 · 永乐',
    born: 1360,
    died: 1424,
    dynastyId: 'ming',
    roles: ['皇帝', '军事家'],
    shortIntro: '明朝第三位皇帝，通过靖难之役夺取皇位，迁都北京，派遣郑和下西洋，编纂《永乐大典》。',
    fullIntro: '明成祖朱棣（1360—1424），明太祖第四子，初封燕王。1399年以“靖难”为名起兵，1402年攻陷南京即位，改元永乐。1421年迁都北京，加强对北方防御；派郑和六下西洋；命人编纂《永乐大典》；五次亲征蒙古，巩固北部边防。',
    achievements: ['迁都北京', '派郑和下西洋', '主持编纂《永乐大典》', '五征蒙古'],
    controversy: '靖难之役后大肆清洗建文旧臣，方孝孺等被诛杀。',
    lifeEvents: [
      { y: 1360, t: '出生' },
      { y: 1402, t: '靖难之役成功，即位称帝' },
      { y: 1421, t: '正式迁都北京' },
      { y: 1424, t: '第五次北征途中病逝' },
    ],
  },
  {
    id: 'zhangjuzheng',
    name: '张居正',
    alias: '张太岳 · 文忠',
    born: 1525,
    died: 1582,
    dynastyId: 'ming',
    roles: ['内阁首辅', '改革家'],
    shortIntro: '明代中后期杰出政治家，万历初年内阁首辅，推行一条鞭法等改革，一度振兴明朝财政。',
    fullIntro: '张居正（1525—1582），字叔大，号太岳，湖广江陵人。嘉靖二十六年进士，隆庆、万历朝官至内阁首辅。任内推行考成法、一条鞭法，清丈田亩，整顿赋役，使明朝财政有所好转；重用戚继光、李成梁等将领，巩固边防。死后被抄家，改革成果多遭反噬。',
    achievements: ['推行一条鞭法', '整顿吏治考成法', '清丈田亩', '巩固边防'],
    controversy: '生前权倾朝野，死后遭弹劾抄家；改革触动既得利益，评价两极。',
    quote: '愿以深心奉尘刹，不予自身求利益。',
    quoteSource: '《张太岳集》',
    lifeEvents: [
      { y: 1525, t: '出生于湖广江陵' },
      { y: 1572, t: '任内阁首辅，辅佐年幼万历帝' },
      { y: 1580, t: '全面推行一条鞭法' },
      { y: 1582, t: '病逝，谥号文忠' },
    ],
  },
  {
    id: 'wangyangming',
    name: '王阳明',
    alias: '王守仁 · 文成',
    born: 1472,
    died: 1529,
    dynastyId: 'ming',
    roles: ['思想家', '军事家', '政治家'],
    shortIntro: '明代心学集大成者，提出“知行合一”“致良知”，平定宁王之乱，文武兼修。',
    fullIntro: '王阳明（1472—1529），名守仁，字伯安，号阳明，浙江余姚人。弘治十二年进士，官至南京兵部尚书。因得罪刘瑾被贬龙场，悟“心即理”，创立阳明心学，主张“知行合一”“致良知”。平定宁王朱宸濠叛乱，事功卓著。',
    achievements: ['创立阳明心学', '平定宁王之乱', '平定两广土司叛乱', '提出知行合一'],
    quote: '知行合一。',
    quoteSource: '《传习录》',
    works: ['《传习录》', '《大学问》'],
    lifeEvents: [
      { y: 1472, t: '出生于浙江余姚' },
      { y: 1506, t: '因触怒刘瑾被贬贵州龙场' },
      { y: 1508, t: '龙场悟道，提出心即理' },
      { y: 1519, t: '平定宁王朱宸濠叛乱' },
      { y: 1529, t: '病逝于江西南安' },
    ],
  },
  {
    id: 'chongzhen',
    name: '朱由检',
    alias: '明思宗 · 崇祯',
    born: 1611,
    died: 1644,
    dynastyId: 'ming',
    roles: ['末代皇帝'],
    shortIntro: '明朝末代皇帝，励精图治但无力回天，1644年李自成攻破北京后自缢于煤山。',
    fullIntro: '明思宗朱由检（1611—1644），年号崇祯，明朝末代皇帝。在位期间铲除魏忠贤，勤政节俭，但面对内忧外患、财政枯竭、党争不断，难以扭转颓势。1644年李自成攻入北京，自缢于煤山，明亡。',
    achievements: ['铲除魏忠贤', '勤政节俭，力图中兴'],
    controversy: '性格多疑，频繁更换内阁首辅；误杀袁崇焕，自毁长城。',
    lifeEvents: [
      { y: 1611, t: '出生' },
      { y: 1627, t: '即位，年号崇祯' },
      { y: 1628, t: '铲除魏忠贤及其党羽' },
      { y: 1630, t: '处死袁崇焕' },
      { y: 1644, t: '李自成破北京，自缢殉国' },
    ],
  },

  // 清朝皇帝与关键人物
  {
    id: 'nurhaci',
    name: '努尔哈赤',
    alias: '清太祖',
    born: 1559,
    died: 1626,
    dynastyId: 'qing',
    roles: ['后金建立者', '军事家'],
    shortIntro: '后金建立者，统一女真各部，创立八旗制度，为清朝建立奠定基础。',
    fullIntro: '努尔哈赤（1559—1626），爱新觉罗氏，女真族。明万历年间统一建州女真，创立八旗制度，1616年建立后金，年号天命。萨尔浒之战击败明军，占据辽东，为清朝入主中原奠定基础。',
    achievements: ['统一女真各部', '创立八旗制度', '建立后金政权', '萨尔浒之战大胜明军'],
    lifeEvents: [
      { y: 1559, t: '出生于建州左卫' },
      { y: 1616, t: '称汗，建立后金' },
      { y: 1619, t: '萨尔浒之战大败明军' },
      { y: 1626, t: '宁远之战负伤，不久去世' },
    ],
  },
  {
    id: 'kangxi',
    name: '玄烨',
    alias: '清圣祖 · 康熙',
    born: 1654,
    died: 1722,
    dynastyId: 'qing',
    roles: ['皇帝', '政治家'],
    shortIntro: '清朝第四位皇帝，在位61年，平定三藩、收复台湾、三征噶尔丹，开创康乾盛世。',
    fullIntro: '清圣祖康熙帝（1654—1722），爱新觉罗氏，8岁即位，16岁擒鳌拜亲政。在位期间平定三藩之乱，收复台湾，击败沙俄签订《尼布楚条约》，三征噶尔丹，巩固多民族国家统一；文治上修《康熙字典》，治理黄河，开创康乾盛世。',
    achievements: ['平定三藩之乱', '收复台湾', '三征噶尔丹', '签订《尼布楚条约》', '治理黄河'],
    controversy: '晚年九子夺嫡，储位之争激烈；文字狱抬头。',
    quote: '正大光明。',
    lifeEvents: [
      { y: 1654, t: '出生' },
      { y: 1661, t: '即位，年号康熙' },
      { y: 1683, t: '收复台湾' },
      { y: 1697, t: '第三次亲征噶尔丹' },
      { y: 1722, t: '病逝于畅春园' },
    ],
  },
  {
    id: 'qianlong',
    name: '弘历',
    alias: '清高宗 · 乾隆',
    born: 1711,
    died: 1799,
    dynastyId: 'qing',
    roles: ['皇帝', '诗人'],
    shortIntro: '清朝第六位皇帝，在位60年，巩固疆域，编纂《四库全书》，晚年吏治腐败，盛世转衰。',
    fullIntro: '清高宗乾隆帝（1711—1799），爱新觉罗氏，雍正帝第四子。在位期间平定准噶尔、大小和卓叛乱，设伊犁将军，巩固新疆；编纂《四库全书》；六下江南，文治武功极盛。但晚年宠信和珅，吏治腐败，白莲教起义爆发，盛世由盛转衰。',
    achievements: ['平定准噶尔与大小和卓', '编纂《四库全书》', '巩固新疆与西藏治理'],
    controversy: '文字狱达到高峰；晚年奢靡，吏治败坏。',
    lifeEvents: [
      { y: 1711, t: '出生' },
      { y: 1735, t: '即位，年号乾隆' },
      { y: 1759, t: '平定大小和卓，设伊犁将军' },
      { y: 1773, t: '开四库全书馆' },
      { y: 1796, t: '禅位嘉庆帝，仍掌实权' },
      { y: 1799, t: '病逝' },
    ],
  },
  {
    id: 'cixi',
    name: '慈禧',
    alias: '慈禧太后 · 孝钦显皇后',
    born: 1835,
    died: 1908,
    dynastyId: 'qing',
    roles: ['皇太后', '实际掌权者'],
    shortIntro: '晚清实际最高统治者，执政近半个世纪，发动戊戌政变，镇压义和团，清末新政主导者。',
    fullIntro: '慈禧太后（1835—1908），叶赫那拉氏，咸丰帝妃，同治帝生母。同治、光绪两朝实际掌权，垂帘听政近半个世纪。任用洋务派，发动戊戌政变镇压维新；利用义和团，招致八国联军侵华；晚年推行清末新政。其统治是晚清保守改革与民族危机交织的缩影。',
    achievements: ['支持洋务运动', '推行清末新政'],
    controversy: '戊戌政变扼杀变法；签订《辛丑条约》；挪用海军经费修颐和园。',
    lifeEvents: [
      { y: 1835, t: '出生' },
      { y: 1861, t: '咸丰帝崩，发动辛酉政变，开始垂帘听政' },
      { y: 1898, t: '发动戊戌政变，囚禁光绪帝' },
      { y: 1900, t: '八国联军侵华，西逃西安' },
      { y: 1908, t: '去世' },
    ],
  },
  {
    id: 'puyi',
    name: '溥仪',
    alias: '宣统帝 · 清逊帝',
    born: 1906,
    died: 1967,
    dynastyId: 'qing',
    roles: ['末代皇帝'],
    shortIntro: '清朝末代皇帝，1912年退位，后曾复辟及任伪满洲国执政，是中国最后一位皇帝。',
    fullIntro: '爱新觉罗·溥仪（1906—1967），清朝末代皇帝，年号宣统。1908年即位，1912年被迫退位；1917年张勋复辟短暂复位；1934年任伪满洲国执政，二战后作为战犯被关押，1959年特赦，后任全国政协委员。著有《我的前半生》。',
    works: ['《我的前半生》'],
    lifeEvents: [
      { y: 1906, t: '出生' },
      { y: 1908, t: '即位' },
      { y: 1912, t: '清帝退位' },
      { y: 1934, t: '任伪满洲国执政' },
      { y: 1945, t: '日本投降，被苏联俘虏' },
      { y: 1967, t: '病逝于北京' },
    ],
  },

  // 晚清人物
  {
    id: 'zengguofan',
    name: '曾国藩',
    alias: '曾涤生 · 文正',
    born: 1811,
    died: 1872,
    dynastyId: 'qing',
    roles: ['晚清重臣', '湘军创立者', '理学家'],
    shortIntro: '晚清政治家、军事家、理学家，湘军的创立者与统帅，洋务运动的早期推动者。',
    fullIntro: '曾国藩，初名子城，字伯涵，号涤生。湖南长沙府湘乡人。道光十八年进士。太平天国运动兴起后，他在湖南募练湘军，历经十余年终于攻陷天京，被清廷倚为柱石。晚年倡导洋务，主张「师夷长技以自强」。',
    achievements: ['编练湘军，平定太平天国', '创办安庆内军械所', '保举李鸿章、左宗棠等名臣', '《曾国藩家书》传世'],
    controversy: '处理天津教案时对外妥协；镇压太平天国手段酷烈，有「曾剃头」之称。',
    quote: '物来顺应，未来不迎，当时不杂，既过不恋。',
    quoteSource: '《曾国藩家书》',
    works: ['《曾国藩家书》', '《曾文正公全集》'],
    lifeEvents: [
      { y: 1811, t: '生于湖南湘乡' },
      { y: 1838, t: '中进士，入翰林院' },
      { y: 1853, t: '奉旨办团练，创立湘军' },
      { y: 1864, t: '攻陷天京，平定太平天国' },
      { y: 1872, t: '病逝于两江总督任上' },
    ],
  },
  {
    id: 'lihongzhang',
    name: '李鸿章',
    alias: '李少荃 · 文忠',
    born: 1823,
    died: 1901,
    dynastyId: 'qing',
    roles: ['晚清重臣', '淮军创立者', '外交家'],
    shortIntro: '晚清重臣，淮军与北洋水师的缔造者，洋务运动的核心人物，晚清外交的主要操盘者。',
    fullIntro: '李鸿章，字渐甫，号少荃，安徽合肥人。早年入曾国藩幕府，后奉命组建淮军。一生历办洋务、创北洋水师、设江南制造与轮船招商，是晚清自强运动的旗帜性人物。然甲午一败，北洋尽墨，又屡签不平等条约，毁誉随之而来。',
    achievements: ['创建淮军与北洋水师', '兴办江南制造总局、轮船招商局', '主持晚清主要外交交涉'],
    controversy: '签订《马关条约》《辛丑条约》，背负卖国骂名。',
    quote: '丈夫只手把吴钩，意气高于百尺楼。',
    quoteSource: '《入都》',
    works: ['《李文忠公全集》'],
    lifeEvents: [
      { y: 1823, t: '生于安徽合肥' },
      { y: 1862, t: '组建淮军，驰援上海' },
      { y: 1870, t: '任直隶总督兼北洋大臣' },
      { y: 1895, t: '签订《马关条约》' },
      { y: 1901, t: '签订《辛丑条约》后病逝' },
    ],
  },

  // 民国人物
  {
    id: 'sunzhongshan',
    name: '孙中山',
    alias: '孙文 · 逸仙',
    born: 1866,
    died: 1925,
    dynastyId: 'roc',
    roles: ['革命家', '政治家', '中华民国缔造者'],
    shortIntro: '中国民主革命先行者，领导辛亥革命推翻清朝，建立中华民国，提出三民主义。',
    fullIntro: '孙中山（1866—1925），名文，字逸仙，广东香山人。早年行医，后投身反清革命，创立兴中会、同盟会，提出民族、民权、民生三民主义。1911年辛亥革命后任中华民国临时大总统，后让位袁世凯。晚年改组国民党，实行联俄联共扶助农工三大政策。',
    achievements: ['领导辛亥革命', '建立中华民国', '提出三民主义', '创立国民党'],
    quote: '革命尚未成功，同志仍须努力。',
    lifeEvents: [
      { y: 1866, t: '出生于广东香山' },
      { y: 1894, t: '创立兴中会' },
      { y: 1905, t: '组建中国同盟会' },
      { y: 1911, t: '辛亥革命爆发' },
      { y: 1912, t: '任中华民国临时大总统' },
      { y: 1925, t: '病逝于北京' },
    ],
  },
  {
    id: 'yuan-shikai',
    name: '袁世凯',
    alias: '袁慰亭 · 项城',
    born: 1859,
    died: 1916,
    dynastyId: 'roc',
    roles: ['政治家', '军事家', '北洋领袖'],
    shortIntro: '清末北洋新军领袖，辛亥革命后任中华民国大总统，后复辟帝制，称帝83天。',
    fullIntro: '袁世凯（1859—1916），字慰亭，河南项城人。清末编练北洋新军，权倾一时。辛亥革命后逼迫清帝退位，任中华民国临时大总统，后当选正式大总统。1915年宣布称帝，改元洪宪，引发护国战争，1916年被迫取消帝制，不久病逝。',
    achievements: ['逼迫清帝退位', '任中华民国首任正式大总统'],
    controversy: '刺杀宋教仁；解散国会；复辟帝制，称帝失败。',
    lifeEvents: [
      { y: 1859, t: '出生于河南项城' },
      { y: 1901, t: '任直隶总督兼北洋大臣' },
      { y: 1912, t: '任中华民国临时大总统' },
      { y: 1915, t: '宣布称帝，改元洪宪' },
      { y: 1916, t: '取消帝制，病逝' },
    ],
  },
  {
    id: 'jiangjieshi',
    name: '蒋介石',
    alias: '蒋中正 · 介石',
    born: 1887,
    died: 1975,
    dynastyId: 'roc',
    roles: ['政治家', '军事家', '国民政府领袖'],
    shortIntro: '国民党领袖，北伐统一中国，领导抗日战争，后在内战中败退台湾。',
    fullIntro: '蒋介石（1887—1975），名中正，字介石，浙江奉化人。黄埔军校校长，北伐军总司令，1928年完成北伐，形式上统一中国。领导中国抗日战争，任国民政府主席、军事委员会委员长。1949年退守台湾，1975年病逝。',
    achievements: ['领导北伐', '形式上统一中国', '领导抗日战争'],
    controversy: '四一二政变清党；围剿苏区；发动内战。',
    lifeEvents: [
      { y: 1887, t: '出生于浙江奉化' },
      { y: 1924, t: '任黄埔军校校长' },
      { y: 1926, t: '出师北伐' },
      { y: 1937, t: '发表庐山谈话，领导全面抗战' },
      { y: 1949, t: '国民政府退守台湾' },
      { y: 1975, t: '病逝于台北' },
    ],
  },
  {
    id: 'maozedong',
    name: '毛泽东',
    alias: '毛润之',
    born: 1893,
    died: 1976,
    dynastyId: 'roc',
    roles: ['革命家', '政治家', '中共领袖'],
    shortIntro: '中国共产党主要创始人之一，领导中共取得内战胜利，建立中华人民共和国。',
    fullIntro: '毛泽东（1893—1976），字润之，湖南湘潭人。中国共产党、中国人民解放军和中华人民共和国的主要缔造者。领导农村包围城市、武装夺取政权的革命道路，取得抗日战争和国共内战胜利，1949年建立中华人民共和国。',
    achievements: ['领导中共革命', '建立中华人民共和国', '提出农村包围城市道路'],
    quote: '星星之火，可以燎原。',
    lifeEvents: [
      { y: 1893, t: '出生于湖南湘潭' },
      { y: 1921, t: '出席中共一大' },
      { y: 1935, t: '遵义会议确立领导地位' },
      { y: 1945, t: '重庆谈判' },
      { y: 1949, t: '中华人民共和国成立' },
      { y: 1976, t: '病逝于北京' },
    ],
  },
];

export const phase1Events = [
  // 明朝事件
  {
    id: 'ming-founded',
    name: '明朝建立',
    startYear: 1368,
    endYear: 1368,
    dynastyId: 'ming',
    place: '南京',
    shortIntro: '朱元璋称帝，国号大明，年号洪武，明朝正式建立。',
    background: '元末红巾军起义后，朱元璋先后击败陈友谅、张士诚等割据势力，北伐驱逐元廷。',
    process: '1368年正月，朱元璋在南京称帝，定国号大明，建元洪武。随后派徐达、常遇春北伐，攻占大都。',
    result: '元朝在中原统治结束，明朝成为全国性政权。',
  },
  {
    id: 'jingnan',
    name: '靖难之役',
    startYear: 1399,
    endYear: 1402,
    dynastyId: 'ming',
    place: '华北、南京',
    shortIntro: '燕王朱棣以“靖难”为名起兵，攻占南京，夺取皇位。',
    background: '明太祖分封诸子为王，燕王朱棣势力最强。建文帝即位后削藩，朱棣不满。',
    process: '1399年，朱棣起兵“靖难”，历时三年，1402年攻陷南京，建文帝下落不明。',
    result: '朱棣即位，改元永乐，即明成祖。',
  },
  {
    id: 'yongle-move-capital',
    name: '永乐迁都',
    startYear: 1421,
    endYear: 1421,
    dynastyId: 'ming',
    place: '北京',
    shortIntro: '明成祖正式迁都北京，确立北京为明朝政治中心。',
    background: '朱棣起家于北方，即位后有意迁都北平以巩固边防、加强对北方控制。',
    process: '1421年正月，明朝正式迁都北京，改北平为顺天府。',
    result: '北京成为明清两代首都，奠定此后中国政治中心格局。',
  },
  {
    id: 'zhenghe',
    name: '郑和下西洋',
    startYear: 1405,
    endYear: 1433,
    dynastyId: 'ming',
    place: '西洋诸国',
    shortIntro: '明成祖至明宣宗时期，郑和七次率船队远航西洋，展现明朝海上实力。',
    background: '明朝国力强盛，为宣扬国威、发展朝贡贸易，派遣郑和出使西洋。',
    process: '1405年至1433年，郑和七次率庞大船队远航，抵达东南亚、印度洋、阿拉伯半岛及东非。',
    result: '加强中国与海外诸国联系，是世界航海史上的壮举。',
  },
  {
    id: 'tumubao',
    name: '土木堡之变',
    startYear: 1449,
    endYear: 1449,
    dynastyId: 'ming',
    place: '土木堡',
    shortIntro: '明英宗朱祁镇亲征瓦剌，兵败被俘，是明朝由盛转衰的标志性事件。',
    background: '明英宗在王振怂恿下亲征瓦剌也先，准备不足。',
    process: '1449年，明军在土木堡被瓦剌包围，英宗被俘，王振被杀。',
    result: '北京危机，于谦等拥立景泰帝，组织北京保卫战；明朝军事威望大损。',
  },
  {
    id: 'zhangjuzheng-reform',
    name: '张居正改革',
    startYear: 1572,
    endYear: 1582,
    dynastyId: 'ming',
    place: '全国',
    shortIntro: '张居正任内阁首辅期间推行考成法、一条鞭法等改革，短暂振兴明朝。',
    background: '明朝中期财政困难、吏治腐败、边防紧张。',
    process: '推行考成法整顿吏治，清丈田亩，一条鞭法改革赋役，重用戚继光等将领。',
    result: '明朝财政和边防一度好转，但张居正死后改革多被废除。',
  },
  {
    id: 'li-zicheng-beijing',
    name: '李自成攻陷北京',
    startYear: 1644,
    endYear: 1644,
    dynastyId: 'ming',
    place: '北京',
    shortIntro: '李自成率领大顺军攻入北京，崇祯帝自缢，明朝灭亡。',
    background: '明末财政枯竭、灾荒频发、农民起义扩大，李自成势力迅速壮大。',
    process: '1644年三月，大顺军攻破北京，崇祯帝在煤山自缢。',
    result: '明朝作为全国性政权结束，清军随后入关。',
  },

  // 清朝事件
  {
    id: 'qing-enter-pass',
    name: '清军入关',
    startYear: 1644,
    endYear: 1644,
    dynastyId: 'qing',
    place: '山海关、北京',
    shortIntro: '吴三桂引清军入关，击败李自成，清朝开始入主中原。',
    background: '李自成攻陷北京后，吴三桂降清，多尔衮率清军入关。',
    process: '1644年四月，山海关之战清军击败大顺军，随后进入北京。',
    result: '清朝定都北京，开始统一全国进程。',
  },
  {
    id: 'sanfan-rebellion',
    name: '平定三藩之乱',
    startYear: 1673,
    endYear: 1681,
    dynastyId: 'qing',
    place: '南方诸省',
    shortIntro: '康熙帝平定吴三桂等三藩叛乱，巩固清朝中央集权。',
    background: '清朝初年封吴三桂、尚之信、耿精忠为三藩，尾大不掉。',
    process: '1673年吴三桂起兵反清，康熙帝调兵遣将，历时八年平定叛乱。',
    result: '消除了地方割据势力，加强了中央对南方控制。',
  },
  {
    id: 'taiwan-recovered',
    name: '收复台湾',
    startYear: 1683,
    endYear: 1683,
    dynastyId: 'qing',
    place: '台湾',
    shortIntro: '康熙帝派施琅攻占台湾，郑氏政权归降，台湾纳入清朝版图。',
    background: '郑成功后代据守台湾，清朝欲统一海疆。',
    process: '1683年，施琅率清军水师在澎湖海战击败郑军，郑克塽投降。',
    result: '台湾正式纳入清朝版图，设台湾府。',
  },
  {
    id: 'opium-war',
    name: '鸦片战争',
    startYear: 1840,
    endYear: 1842,
    dynastyId: 'qing',
    place: '广东、浙江、江苏沿海',
    shortIntro: '英国以林则徐虎门销烟为借口发动侵华战争，清朝战败，签订《南京条约》。',
    background: '清朝禁烟运动打击英国鸦片贸易，英国决定以武力打开中国市场。',
    process: '1840年英军封锁珠江口，进攻沿海城市，清军节节败退。',
    result: '签订中国近代史上第一个不平等条约《南京条约》，中国开始沦为半殖民地半封建社会。',
  },
  {
    id: 'taiping',
    name: '太平天国运动',
    startYear: 1851,
    endYear: 1864,
    dynastyId: 'qing',
    place: '长江中下游',
    shortIntro: '洪秀全领导的农民起义，建立太平天国，席卷半个中国，最终被湘军镇压。',
    background: '晚清吏治腐败、赋役沉重、自然灾害频繁，民众反抗情绪高涨。',
    process: '1851年金田起义，1853年定都天京，1864年湘军攻陷天京。',
    result: '清朝元气大伤，汉族地方武装崛起，加速晚清权力结构变化。',
  },
  {
    id: 'yangwu',
    name: '洋务运动',
    startYear: 1861,
    endYear: 1895,
    dynastyId: 'qing',
    place: '全国',
    shortIntro: '清朝官僚推动的自强求富运动，创办近代工业、海军、新式学堂。',
    background: '第二次鸦片战争后，清廷面临内忧外患，奕訢、曾国藩、李鸿章等主张学习西方技术。',
    process: '创办江南制造总局、轮船招商局、北洋水师等近代企业与军事力量。',
    result: '开启中国近代化进程，但甲午战争失败标志洋务运动破产。',
  },
  {
    id: 'jiawu',
    name: '甲午战争',
    startYear: 1894,
    endYear: 1895,
    dynastyId: 'qing',
    place: '朝鲜半岛、黄海、辽东、山东',
    shortIntro: '清朝与日本因朝鲜问题爆发战争，清朝战败，签订《马关条约》。',
    background: '中日同时干涉朝鲜内政，矛盾激化。',
    process: '1894年丰岛海战爆发，清军陆海两线失利，北洋水师在威海卫覆没。',
    result: '签订《马关条约》，割让台湾、澎湖，赔款二亿两白银，中国国际地位骤降。',
  },
  {
    id: 'wuxu',
    name: '戊戌变法',
    startYear: 1898,
    endYear: 1898,
    dynastyId: 'qing',
    place: '北京',
    shortIntro: '光绪帝支持康有为、梁启超等推行政治改革，历时103天被慈禧太后镇压。',
    background: '甲午战败后民族危机加深，维新派主张君主立宪、改革教育军事。',
    process: '1898年6月光绪帝颁布变法诏令，9月慈禧发动政变，囚禁光绪，戊戌六君子遇害。',
    result: '变法失败，但推动了中国近代思想启蒙。',
  },
  {
    id: 'xinhai',
    name: '辛亥革命',
    startYear: 1911,
    endYear: 1912,
    dynastyId: 'qing',
    place: '武昌、全国',
    shortIntro: '孙中山领导的资产阶级民主革命，推翻清朝统治，结束中国两千多年帝制。',
    background: '清末民族危机、立宪失败、革命团体兴起。',
    process: '1911年10月10日武昌起义爆发，各省纷纷响应，1912年清帝退位。',
    result: '中华民国建立，中国帝制时代终结。',
  },
  {
    id: 'qing-abdication',
    name: '清帝退位',
    startYear: 1912,
    endYear: 1912,
    dynastyId: 'qing',
    place: '北京',
    shortIntro: '溥仪颁布退位诏书，清朝灭亡，中国延续两千多年的君主制结束。',
    background: '辛亥革命后各省独立，袁世凯与革命党谈判，逼迫清帝退位。',
    process: '1912年2月12日，隆裕太后代溥仪颁布退位诏书。',
    result: '清朝正式灭亡，袁世凯任中华民国临时大总统。',
  },

  // 民国事件
  {
    id: 'may-fourth',
    name: '五四运动',
    startYear: 1919,
    endYear: 1919,
    dynastyId: 'roc',
    place: '北京、上海',
    shortIntro: '以学生为先锋的反帝反封建爱国运动，标志新民主主义革命开端。',
    background: '巴黎和会将德国在山东权益转交日本，引发民众强烈不满。',
    process: '1919年5月4日北京学生游行抗议，随后工人罢工、商人罢市，运动扩展至全国。',
    result: '中国代表拒绝在《巴黎和约》上签字，马克思主义广泛传播。',
  },
  {
    id: 'northern-expedition',
    name: '北伐战争',
    startYear: 1926,
    endYear: 1928,
    dynastyId: 'roc',
    place: '华南、华中、华北',
    shortIntro: '国民革命军北进讨伐北洋军阀，基本结束军阀割据局面。',
    background: '国民政府在广州建立，决意统一全国。',
    process: '1926年国民革命军从广东出师北伐，击败吴佩孚、孙传芳等军阀，1928年张学良东北易帜。',
    result: '南京国民政府在形式上统一中国。',
  },
  {
    id: 'mukden-incident',
    name: '九一八事变',
    startYear: 1931,
    endYear: 1931,
    dynastyId: 'roc',
    place: '沈阳',
    shortIntro: '日本关东军炸毁南满铁路，进攻东北军，侵占中国东北。',
    background: '日本蓄谋侵略中国东北，制造事端。',
    process: '1931年9月18日夜，日军炸毁柳条湖铁路，反诬中国军队所为，进攻北大营。',
    result: '东北三省迅速沦陷，日本扶植伪满洲国。',
  },
  {
    id: 'xian-incident',
    name: '西安事变',
    startYear: 1936,
    endYear: 1936,
    dynastyId: 'roc',
    place: '西安',
    shortIntro: '张学良、杨虎城发动兵谏，逼蒋抗日，促成第二次国共合作。',
    background: '国民政府坚持“攘外必先安内”，民众抗日呼声高涨。',
    process: '1936年12月12日，张学良、杨虎城扣押蒋介石，中共派周恩来谈判。',
    result: '蒋介石被迫接受停止内战、一致抗日主张，抗日民族统一战线初步形成。',
  },
  {
    id: 'anti-japanese-war',
    name: '抗日战争',
    startYear: 1937,
    endYear: 1945,
    dynastyId: 'roc',
    place: '中国全境',
    shortIntro: '中华民族抗击日本侵略的全民族战争，1945年取得完全胜利。',
    background: '日本发动全面侵华战争，国共两党再度合作。',
    process: '1937年七七事变爆发，中国全面抗战开始；正面战场与敌后战场相互配合，1945年日本投降。',
    result: '中国近代以来第一次取得反侵略战争的完全胜利，国际地位提高。',
  },
  {
    id: 'civil-war',
    name: '国共内战',
    startYear: 1946,
    endYear: 1949,
    dynastyId: 'roc',
    place: '中国全境',
    shortIntro: '抗日战争胜利后，国民党与共产党爆发全面内战，最终中共取得胜利。',
    background: '抗战胜利后国共矛盾激化，重庆谈判未能阻止内战。',
    process: '1946年全面内战爆发，解放军由战略防御转入战略进攻，1949年攻占南京。',
    result: '1949年中华人民共和国成立，国民政府退守台湾。',
  },
];

export const phase1Relations = [
  { sourceId: 'hongwu', targetId: 'yongle', relationType: 'FATHER_OF', label: '父子', description: '明太祖朱元璋第四子燕王朱棣发动靖难之役夺取皇位。' },
  { sourceId: 'yongle', targetId: 'hongwu', relationType: 'SON_OF', label: '父子', description: '朱棣为朱元璋第四子。' },
  { sourceId: 'zhangjuzheng', targetId: 'yongle', relationType: 'ADMIRED', label: '推崇', description: '张居正以永乐朝集权体制为参照推行改革。' },
  { sourceId: 'wangyangming', targetId: 'zhangjuzheng', relationType: 'CONTEMPORARY_OF', label: '同时代人', description: '王阳明与张居正生活年代相近，思想与事功分别代表明代中期的文化与政治高峰。' },
  { sourceId: 'chongzhen', targetId: 'li-zicheng-beijing', relationType: 'VICTIM_OF', label: '终结', description: '崇祯帝在李自成攻陷北京后自缢。' },
  { sourceId: 'nurhaci', targetId: 'kangxi', relationType: 'GRANDFATHER_OF', label: '祖孙', description: '努尔哈赤为康熙帝曾祖父，奠定后金基业。' },
  { sourceId: 'kangxi', targetId: 'qianlong', relationType: 'GRANDFATHER_OF', label: '祖孙', description: '康熙帝为乾隆帝祖父，康雍乾三代共创盛世。' },
  { sourceId: 'cixi', targetId: 'wuxu', relationType: 'OPPOSED', label: '镇压', description: '慈禧太后发动戊戌政变，镇压变法。' },
  { sourceId: 'zengguofan', targetId: 'lihongzhang', relationType: 'TEACHER_OF', label: '师生', description: '李鸿章入曾国藩幕府，受其栽培。' },
  { sourceId: 'zengguofan', targetId: 'taiping', relationType: 'OPPOSED', label: '敌对', description: '曾国藩率湘军镇压太平天国运动。' },
  { sourceId: 'lihongzhang', targetId: 'jiawu', relationType: 'PARTICIPATED_IN', label: '参与', description: '李鸿章主持甲午战争外交与军事统筹。' },
  { sourceId: 'sunzhongshan', targetId: 'yuan-shikai', relationType: 'SUCCESSOR_OF', label: '让位', description: '孙中山辞去临时大总统，让位袁世凯。' },
  { sourceId: 'yuan-shikai', targetId: 'qing-abdication', relationType: 'FORCED', label: '逼迫', description: '袁世凯逼迫清帝退位。' },
  { sourceId: 'jiangjieshi', targetId: 'northern-expedition', relationType: 'LED', label: '领导', description: '蒋介石任国民革命军总司令，领导北伐。' },
  { sourceId: 'maozedong', targetId: 'jiangjieshi', relationType: 'RIVAL_OF', label: '政敌', description: '毛泽东与蒋介石分别代表国共两党，长期对立。' },
  { sourceId: 'maozedong', targetId: 'anti-japanese-war', relationType: 'PARTICIPATED_IN', label: '参与', description: '毛泽东领导中共敌后抗日根据地。' },
];

export const phase1PersonEvents = [
  { personId: 'hongwu', eventId: 'ming-founded', role: '主导' },
  { personId: 'yongle', eventId: 'jingnan', role: '主导' },
  { personId: 'yongle', eventId: 'yongle-move-capital', role: '主导' },
  { personId: 'yongle', eventId: 'zhenghe', role: '主导' },
  { personId: 'zhangjuzheng', eventId: 'zhangjuzheng-reform', role: '主导' },
  { personId: 'chongzhen', eventId: 'li-zicheng-beijing', role: '殉国' },
  { personId: 'kangxi', eventId: 'sanfan-rebellion', role: '主导' },
  { personId: 'kangxi', eventId: 'taiwan-recovered', role: '主导' },
  { personId: 'qianlong', eventId: 'opium-war', role: '前期统治者' },
  { personId: 'cixi', eventId: 'wuxu', role: '镇压者' },
  { personId: 'cixi', eventId: 'opium-war', role: '实际决策者' },
  { personId: 'puyi', eventId: 'qing-abdication', role: '退位皇帝' },
  { personId: 'zengguofan', eventId: 'taiping', role: '镇压者' },
  { personId: 'zengguofan', eventId: 'yangwu', role: '推动者' },
  { personId: 'lihongzhang', eventId: 'jiawu', role: '主政者' },
  { personId: 'lihongzhang', eventId: 'yangwu', role: '推动者' },
  { personId: 'sunzhongshan', eventId: 'xinhai', role: '领导者' },
  { personId: 'sunzhongshan', eventId: 'qing-abdication', role: '革命领袖' },
  { personId: 'yuan-shikai', eventId: 'qing-abdication', role: '逼迫者' },
  { personId: 'jiangjieshi', eventId: 'northern-expedition', role: '总司令' },
  { personId: 'jiangjieshi', eventId: 'anti-japanese-war', role: '最高领袖' },
  { personId: 'maozedong', eventId: 'anti-japanese-war', role: '敌后抗战领导者' },
  { personId: 'maozedong', eventId: 'civil-war', role: '中共统帅' },
];
